# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='message_submitted', to='test_app.User'),
            preserve_default=False,
        ),
    ]
